include_guard(GLOBAL)

function(openmeta_report_dependency name enabled found provider)
  if(NOT enabled)
    message(STATUS "    ${name}: OFF (not required)")
    return()
  endif()

  if(found)
    if(provider)
      message(STATUS "    ${name}: FOUND (${provider})")
    else()
      message(STATUS "    ${name}: FOUND")
    endif()
  else()
    message(STATUS "    ${name}: NOTFOUND")
  endif()
endfunction()

function(openmeta_print_config_summary)
  message(STATUS "OpenMeta configuration summary:")
  message(STATUS "  Generator: ${CMAKE_GENERATOR}")
  if(CMAKE_CONFIGURATION_TYPES)
    message(STATUS "  Configurations: ${CMAKE_CONFIGURATION_TYPES}")
  else()
    if(CMAKE_BUILD_TYPE)
      message(STATUS "  Build type: ${CMAKE_BUILD_TYPE}")
    else()
      message(STATUS "  Build type: <not set>")
    endif()
  endif()
  message(STATUS "  C++ compiler: ${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION}")
  message(STATUS "  C++ compiler path: ${CMAKE_CXX_COMPILER}")
  if(CMAKE_PREFIX_PATH)
    message(STATUS "  CMAKE_PREFIX_PATH: ${CMAKE_PREFIX_PATH}")
  else()
    message(STATUS "  CMAKE_PREFIX_PATH: <empty>")
  endif()
  if(OPENMETA_DEPS_REPOS_ROOT)
    message(STATUS "  OPENMETA_DEPS_REPOS_ROOT: ${OPENMETA_DEPS_REPOS_ROOT}")
  endif()
  message(STATUS "  Options:")
  message(STATUS "    OPENMETA_BUILD_STATIC: ${OPENMETA_BUILD_STATIC}")
  message(STATUS "    OPENMETA_BUILD_SHARED: ${OPENMETA_BUILD_SHARED}")
  message(STATUS "    OPENMETA_BUILD_TOOLS: ${OPENMETA_BUILD_TOOLS}")
  message(STATUS "    OPENMETA_BUILD_TESTS: ${OPENMETA_BUILD_TESTS}")
  message(STATUS "    OPENMETA_BUILD_FUZZERS: ${OPENMETA_BUILD_FUZZERS}")
  message(STATUS "    OPENMETA_BUILD_FUZZTEST: ${OPENMETA_BUILD_FUZZTEST}")
  message(STATUS "    OPENMETA_FUZZTEST_FUZZING_MODE: ${OPENMETA_FUZZTEST_FUZZING_MODE}")
  message(STATUS "    OPENMETA_BUILD_DOCS: ${OPENMETA_BUILD_DOCS}")
  message(STATUS "    OPENMETA_BUILD_SPHINX_DOCS: ${OPENMETA_BUILD_SPHINX_DOCS}")
  message(STATUS "    OPENMETA_BUILD_PYTHON: ${OPENMETA_BUILD_PYTHON}")
  message(STATUS "    OPENMETA_BUILD_WHEEL: ${OPENMETA_BUILD_WHEEL}")
  if(OPENMETA_PYTHON_EXECUTABLE)
    message(STATUS "    OPENMETA_PYTHON_EXECUTABLE: ${OPENMETA_PYTHON_EXECUTABLE}")
  endif()
  message(STATUS "    OPENMETA_WITH_ZLIB: ${OPENMETA_WITH_ZLIB}")
  message(STATUS "    OPENMETA_WITH_BROTLI: ${OPENMETA_WITH_BROTLI}")
  message(STATUS "    OPENMETA_WITH_EXPAT: ${OPENMETA_WITH_EXPAT}")
  message(STATUS "    OPENMETA_USE_LIBCXX: ${OPENMETA_USE_LIBCXX}")
  message(STATUS "  Dependencies:")
  message(STATUS "    Core library:")
  openmeta_report_dependency("ZLIB (deflate)" "${OPENMETA_WITH_ZLIB}" "${OPENMETA_ZLIB_FOUND}" "system")
  openmeta_report_dependency("Brotli" "${OPENMETA_WITH_BROTLI}" "${OPENMETA_BROTLI_FOUND}" "system")
  openmeta_report_dependency("EXPAT (XMP XML)" "${OPENMETA_WITH_EXPAT}" "${OPENMETA_EXPAT_FOUND}" "system")
  if(OPENMETA_BUILD_PYTHON OR OPENMETA_BUILD_WHEEL OR OPENMETA_BUILD_SPHINX_DOCS)
    message(STATUS "    Python:")
    set(py_found OFF)
    set(py_provider "system")
    if(DEFINED OPENMETA_PYTHON_VERSION AND OPENMETA_PYTHON_VERSION)
      set(py_found ON)
      set(py_provider "Python ${OPENMETA_PYTHON_VERSION}")
    elseif(DEFINED Python_VERSION AND Python_VERSION)
      set(py_found ON)
      set(py_provider "Python ${Python_VERSION}")
    elseif(DEFINED _Python_EXECUTABLE AND _Python_EXECUTABLE)
      set(py_found ON)
    endif()
    openmeta_report_dependency("Python" "ON" "${py_found}" "${py_provider}")
    if(DEFINED Python_EXECUTABLE AND Python_EXECUTABLE)
      message(STATUS "      Python_EXECUTABLE: ${Python_EXECUTABLE}")
    endif()

    set(nanobind_found OFF)
    if(DEFINED OPENMETA_NANOBIND_FOUND AND OPENMETA_NANOBIND_FOUND)
      set(nanobind_found ON)
    elseif(DEFINED nanobind_FOUND AND nanobind_FOUND)
      set(nanobind_found ON)
    elseif(DEFINED nanobind_DIR AND nanobind_DIR)
      set(nanobind_found ON)
    endif()
    openmeta_report_dependency("nanobind" "${OPENMETA_BUILD_PYTHON}" "${nanobind_found}" "system (config)")
  else()
    message(STATUS "    Python: OFF (not required)")
  endif()

  message(STATUS "    Tools: none")

  set(gtest_found OFF)
  if(TARGET gtest_main)
    set(gtest_found ON)
  endif()
  openmeta_report_dependency("GoogleTest" "${OPENMETA_BUILD_TESTS}" "${gtest_found}" "${OPENMETA_GTEST_PROVIDER}")

  set(fuzztest_found OFF)
  if(TARGET fuzztest::fuzztest)
    set(fuzztest_found ON)
  endif()
  openmeta_report_dependency("FuzzTest" "${OPENMETA_BUILD_FUZZTEST}" "${fuzztest_found}"
    "${OPENMETA_FUZZTEST_PROVIDER}")

  if(NOT OPENMETA_BUILD_FUZZERS)
    message(STATUS "    libFuzzer: OFF (not required)")
  else()
    message(STATUS "    libFuzzer: FOUND (Clang)")
  endif()

  set(doxygen_found OFF)
  if(DEFINED DOXYGEN_FOUND AND DOXYGEN_FOUND)
    set(doxygen_found ON)
  endif()

  set(_openmeta_docs_enabled OFF)
  if(OPENMETA_BUILD_DOCS OR OPENMETA_BUILD_SPHINX_DOCS)
    set(_openmeta_docs_enabled ON)
  endif()
  openmeta_report_dependency("Doxygen" "${_openmeta_docs_enabled}" "${doxygen_found}" "system")

  set(sphinx_found OFF)
  if(DEFINED OPENMETA_SPHINX_FOUND AND OPENMETA_SPHINX_FOUND)
    set(sphinx_found ON)
  endif()
  openmeta_report_dependency("Sphinx" "${OPENMETA_BUILD_SPHINX_DOCS}" "${sphinx_found}" "Python module")

  set(breathe_found OFF)
  if(DEFINED OPENMETA_BREATHE_FOUND AND OPENMETA_BREATHE_FOUND)
    set(breathe_found ON)
  endif()
  openmeta_report_dependency("Breathe" "${OPENMETA_BUILD_SPHINX_DOCS}" "${breathe_found}" "Python module")
endfunction()
