include_guard(GLOBAL)

function(openmeta_report_dependency name enabled found provider)
  if(NOT enabled)
    message(STATUS "    ${name}: OFF (not required)")
    return()
  endif()

  if(found)
    if(provider)
      message(STATUS "    ${name}: FOUND (${provider})")
    else()
      message(STATUS "    ${name}: FOUND")
    endif()
  else()
    message(STATUS "    ${name}: NOTFOUND")
  endif()
endfunction()

function(openmeta_print_config_summary)
  message(STATUS "OpenMeta configuration summary:")
  message(STATUS "  Generator: ${CMAKE_GENERATOR}")
  if(CMAKE_CONFIGURATION_TYPES)
    message(STATUS "  Configurations: ${CMAKE_CONFIGURATION_TYPES}")
  else()
    if(CMAKE_BUILD_TYPE)
      message(STATUS "  Build type: ${CMAKE_BUILD_TYPE}")
    else()
      message(STATUS "  Build type: <not set>")
    endif()
  endif()
  message(STATUS "  C++ compiler: ${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION}")
  message(STATUS "  C++ compiler path: ${CMAKE_CXX_COMPILER}")
  message(STATUS "  CMAKE_PREFIX_PATH: ${CMAKE_PREFIX_PATH}")
  if(OPENMETA_DEPS_REPOS_ROOT)
    message(STATUS "  OPENMETA_DEPS_REPOS_ROOT: ${OPENMETA_DEPS_REPOS_ROOT}")
  endif()
  message(STATUS "  Options:")
  message(STATUS "    OPENMETA_BUILD_STATIC: ${OPENMETA_BUILD_STATIC}")
  message(STATUS "    OPENMETA_BUILD_SHARED: ${OPENMETA_BUILD_SHARED}")
  message(STATUS "    OPENMETA_BUILD_TOOLS: ${OPENMETA_BUILD_TOOLS}")
  message(STATUS "    OPENMETA_BUILD_TESTS: ${OPENMETA_BUILD_TESTS}")
  message(STATUS "    OPENMETA_BUILD_FUZZERS: ${OPENMETA_BUILD_FUZZERS}")
  message(STATUS "    OPENMETA_BUILD_FUZZTEST: ${OPENMETA_BUILD_FUZZTEST}")
  message(STATUS "    OPENMETA_FUZZTEST_FUZZING_MODE: ${OPENMETA_FUZZTEST_FUZZING_MODE}")
  message(STATUS "  Dependencies:")
  message(STATUS "    Core library: none")
  message(STATUS "    Tools: none")

  set(gtest_found OFF)
  if(TARGET gtest_main)
    set(gtest_found ON)
  endif()
  openmeta_report_dependency("GoogleTest" "${OPENMETA_BUILD_TESTS}" "${gtest_found}" "${OPENMETA_GTEST_PROVIDER}")

  set(fuzztest_found OFF)
  if(TARGET fuzztest::fuzztest)
    set(fuzztest_found ON)
  endif()
  openmeta_report_dependency("FuzzTest" "${OPENMETA_BUILD_FUZZTEST}" "${fuzztest_found}"
    "${OPENMETA_FUZZTEST_PROVIDER}")

  if(NOT OPENMETA_BUILD_FUZZERS)
    message(STATUS "    libFuzzer: OFF (not required)")
  else()
    message(STATUS "    libFuzzer: FOUND (Clang)")
  endif()
endfunction()
